---
cache:
   job:
       main: [~/.m2/repository/]
jobs:
  main:
    annotations:
      screwdriver.cd/ram: HIGH
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/disk: HIGH
    environment:
      ARTIFACTORY_REPO: BDAI
      BASE_DIR: /sd/workspace/src/git.ouroath.com/BDAI-TEST
    #
    image: docker.ouroath.com:4443/sd_bdai_baseimg/bdai_baseimg:bdai_base
    requires: [~pr, ~commit]
    steps:
      - init: |
           set -x
           mvn --version
           env
           uname -a
           cat /proc/meminfo
           vmstat -s
           ps -edf
           mkdir -p  ~/.m2/repository
           cp /bdai/usr/bin/m2_settings.xml ~/.m2/settings.xml
      - build: |
           cat ~/.m2/settings.xml
           # Build failed with tests execution, skip tests until resolve
           #mvn -U clean deploy -DskipTests
           mvn -U clean install -DskipTests
